version: "3"

silent: true

tasks:
  up:
    desc: "Start the development services"
    cmds:
      - docker compose -f ./compose/docker-compose.yml up -d

  down:
    desc: "Stop the development services"
    cmds:
      - docker compose -f ./compose/docker-compose.yml down

  delete:
    desc: "WARNING: Stop the development services and remove all data"
    cmds:
      - docker compose -f ./compose/docker-compose.yml down --volumes
